### ISSUE TITLE
Excecption Ticking World

### ISSUE THREAD

**Issue by ablehobo** [Glitchfiend/SereneSeasons#451]
### What's the issue you encountered?

Am running version 9.3.0.15 on a Fabric server.  When updating to version 9.3.0.16+ the game crashes on startup.  I am able to revert to version .15 and it loads fine.

### How can the issue be reproduced?

Create a world with mod version 9.3.0.15 on Fabric server and update mod version to 9.3.0.16+.

### Logs

https://gist.github.com/ablehobo/cb6123e9d8418283f86967e9860b8c6d

### Mod Version

9.3.0.16

### Additional information

Love the work you do.  Looking forward to update to .17 to fix the ice issue we are experiencing as well.  Thanks again!  And if I need to provide any more information please let me know how to help.

**Comment by Forstride** [comment]
Deleting your existing config should fix it

**Comment by ablehobo** [comment]
I still get the same error after deleting /config/sereneseasons and /world/data/seasons.dat.  Is there another config that I am missing?  Thank you.

**Comment by Adubbz** [comment]
Try updating the mod to .18

**Comment by ablehobo** [comment]
Issue resolved after updating to .18.
